---
- name: Install IIS
  hosts: all
  gather_facts: true
  tasks:
    - 
       name: Install IIS (Web-Server only)
       ansible.windows.win_feature:
        name: Web-Server
        state: present
        restart: yes

   # - 
     #  name: Copy index test page
       #.windows.win_copy:
          #src: files/index.html
          #dest: C:\\inetpub\\wwwroot\index.html
      # notify: Restart IIS service 

  #handlers:
    #- 
      # name: Restart IIS service
       #ansible.windows.win_service:
        #name: iis
        #state: restarted
