---
- name: Create a file and write content to it
  hosts: all
  become: yes
  tasks:
    - name: Ensure the file exists
      command: echo "Hi Fapathe Fall" >> /home/base/info_gmd.txt
     # file:
     #   path: /home/base/info_gmd.txt
      #  state: touch
      
       
