---
- name: Créer un fichier et ajouter du contenu
  hosts: all
  become: yes
  tasks:
    - name: Ajouter une ligne dans le fichier /tmp/infos.txt
      lineinfile:
        path: /tmp/infos.txt
        line: "GMD automatisé avec Ansible le {{ ansible_date_time.iso8601 }}"
        create: yes

