---
- name: Install Kaspersky on Windows
  hosts: all
  gather_facts: true
  

  tasks:
    - name: Copy Kaspersky Installer to Windows Server
      win_copy:
        src: \\192.168.14.210\Accel_Technologies\Software\kaspersky\startup.exe
        dest: C:\temp\kaspersky_installer.exe

    - name: Install Kaspersky
      win_shell: |
        Start-Process -Wait -FilePath "C:\temp\kaspersky_installer.exe" -ArgumentList "/silent"
      args:
        executable: powershell.exe

    - name: Remove Kaspersky Installer
      win_file:
        path: C:\temp\kaspersky_installer.exe
        state: absent

