 
---
- name: Install Kaspersky on Windows Server
  hosts: all
  become: true

  tasks:
    - name: Download Kaspersky Installer
      win_get_url:
        url: "https://www.kaspersky.com/downloads/antivirus"
        dest: "C:\Temp\kaspersky_installer.exe"

    - name: Install Kaspersky
      win_shell: |
        Start-Process -Wait -FilePath "C:\Temp\kaspersky_installer.exe" -ArgumentList "/silent /install"
      args:
        executable: powershell.exe

    - name: Clean up temporary files
      win_shell: Remove-Item -Path "C:\Temp\kaspersky_installer.exe" -Force

