---
- name: Install Kaspersky on Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Download Kaspersky installer
      win_shell: |
        $url = "https://www.kaspersky.fr/downloads/antivirus"  # Replace with the actual download link
        $output = "C:\temp\kaspersky_installer.exe"  # Change the destination folder and filename as needed
        Invoke-WebRequest -Uri $url -OutFile $output
     

    - name: Install Kaspersky
      win_shell: |
        Start-Process -FilePath "C:\temp\kaspersky_installer.exe" -ArgumentList "/silent" -Wait
      args:
        executable: powershell.exe
   

    - name: Clean up installer
      win_shell: Remove-Item -Path "C:\temp\kaspersky_installer.exe" -Force
      
