- name: Install 7-Zip on Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Download 7-Zip installer
      win_command: "Invoke-WebRequest -Uri 'https://www.7-zip.org/a/7z{{ version }}-x64.msi' -OutFile 'C:\\temp\\7zip.msi'"
      vars:
        version: "1900"

    - name: Install 7-Zip
      win_command: "Start-Process msiexec.exe -Wait -ArgumentList '/i C:\\temp\\7zip.msi /quiet /norestart'"
      become: yes

    - name: Clean up temporary files
      win_command: "Remove-Item 'C:\\temp\\7zip.msi' -Force"
