---
- name: Install 7-Zip on Windows Server
  hosts: all
  tasks:  
      - name: Download the 7-Zip package
        win_get_url:
          url: https://www.7-zip.org/a/7z2301-x64.msi
          dest: C:\temp\7z.msi

      - name: Ensure 7-Zip is installed through win_package
        win_package:
           path: C:\temp\7z.msi
           state: present
