---
- name: Install packages on systems
  hosts: all
  vars:
    packages:
      - Putty
      - Kasperky

  tasks:
    - name: Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Packages are installed
      win_chocolatey:
        name: "{{ packages }}"
        state: present
        pinned: true
      register: install_result

    - name: Server is rebooted
      win_reboot:
      when: install_result.changed and install_result.rc == 3010
