 
---
- name: Install Kaspersky on Windows Server
  hosts: all
  
  tasks:
   
      - name: Download the 7-Zip package
        win_get_url:
            url: https://www.7-zip.org/a/7z2301-x64.exe
            dest: C:\temp\

      - name: Ensure 7-Zip is installed through win_package
        win_command: C:\Windows\System32\7z2301-x64.exe /i C:\temp\7z2301-x64.exe /qn /norestart
