---
- name: Maintain Access Control Lists on Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Set ACL on a directory
      win_acl:
        path: C:\Windows
        user: username
        rights:
          - GenericAll
        type: allow

    - name: Set ACL on a file
      win_acl:
        path: C:\aap\test.txt
        user: username
        rights:
          - GenericRead
          - GenericWrite
        type: allow

    - name: Remove a specific user from ACL
      win_acl:
        path: C:\Windows
        user: username_to_remove
        state: absent
