---
- name: Maintain Access Control Lists on Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Create a user named fama
      win_user:
         name: fama1
         password: fama
         groups: standard
         state: present
    - name: Set ACL on a directory
      win_acl:
        path: C:\Windows
        user: fama1
        rights: Read
        type: FullControl
        state: present

    - name: Set ACL on a file
      win_acl:
        path: C:\aap\test.txt
        user: fama1
        rights: FullControl
        type: allow
        state: present

    #- name: Remove a specific user from ACL 
     # win_acl:
       # path: C:\Windows
       # user: fama
       # state: absent
