---
- name: Add User to Active Directory
  hosts: all
  become: yes
  tasks:
    - name: Create AD User
      win_domain_user:
        domain_account: "lab.local"
        username: fama
        password: Passer@123
        state: present
        groups:
          - developers
