---
- name: Maintain Access Control Lists on Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Create a user named fama
      win_user:
         name: fama
         password: fama
         state: present
    - name: Set ACL on a directory
      win_acl:
        path: C:\Windows
        user: fama
        rights:
          - GenericAll
        type: allow

    - name: Set ACL on a file
      win_acl:
        path: C:\aap\test.txt
        user: fama
        rights:
          - GenericRead
          - GenericWrite
        type: allow

    - name: Remove a specific user from ACL
      win_acl:
        path: C:\Windows
        user: fama
        state: absent
