---
- name: Maintain Access Control Lists on Windows
  hosts: all
  gather_facts: true
  tasks:
    - name: Create a user named Abdou
      win_user:
         name: abdou
         password: Abdou3096
         state: present
    - name: Set ACL on a directory
      win_acl:
        path: C:\Windows
        user: abdou
        rights: FullControl
        type: allow
        state: present

    - name: Set ACL on a file
      win_acl:
        path: C:\aap\test.txt
        user: abdou
        rights: Read
        type: deny
        state: present

    #- name: Remove a specific user from ACL 
     # win_acl:
       # path: C:\Windows
       # user: fama
       # state: absent
