---
- name: Manage Windows Reboot
  hosts: all
  gather_facts: false
  tasks:
    - name: Initiate Reboot
      ansible.builtin.win_reboot:
        reboot_timeout: 300
        pre_reboot_delay: 0
      register: reboot_result
      ignore_errors: true

    - name: Wait for system to come back up
      ansible.builtin.wait_for_connection:
        timeout: 300
      when: reboot_result.reboot_required

    - name: Display a message after reboot
      ansible.builtin.debug:
        msg: "System has been rebooted successfully."
