---
- name: Manage Windows Reboot
  hosts: all
  gather_facts: false
  tasks:
    - name: Initiate Reboot
      ansible.builtin.win_reboot:
        reboot_timeout: 600
        pre_reboot_delay: 0
      register: reboot_result
      ignore_errors: true

    - name: Display a message after reboot
      ansible.builtin.debug:
        msg: "System has been rebooted successfully."
