---
- name: Créer le fichier /tmp/gmd/info.txt
  hosts: all
  become: yes
  tasks:
    - name: Créer le fichier vide
      file:
        path: /tmp/gmd/info.txt
        state: touch
        mode: '0644'
