---
- name: using windows powershell
  hosts: all
  gather_facts: true
  tasks:
   - name: Single line PowerShell
     win_shell: Set-Content -Path C:\aap\test.txt -Value 'Hello from the other side'
 
       
   - name: Run the powersher script
     win_shell:  C:\aap\hello.ps1 >>  C:\aap\output.txt
