---
- name: Customize Windows Registry
  hosts: all
  gather_facts: true
  tasks:
    - name: create a new Registry 
      win_regedit:
        path: "HKEY_USERS:\\Software\\Example"
    - name: modifying the registry adding name data and type
      win_regedit:
        path:  "HKEY_USERS:\\Software\\Example"
        name: Ansible
        data: playbook
        type: string
