---
- name: Add Server to Domain
  hosts: all
  gather_facts: true
  tasks:
    - name: dns client
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses: 192.168.14.140
    - name: Add a local and domain user to a local group
      ansible.windows.win_group_membership:
        name: WORKGROUP
        members:
           - TEST\Administrateur
        state: present

    - name: Join server to domain
      win_domain_membership:
        dns_domain_name: test.com
        hostname: "{{ ansible_hostname }}"
        domain_admin_user: Administrateur
        domain_admin_password: Passer@123
        state: domain
      register: domain_membership_result

    - name: Reboot if required
      when: domain_membership_result.reboot_required
      win_reboot:


