---
- name: Customize Windows Registry
  hosts: all
  gather_facts: false
  tasks:
    - name: create a new Registry 
      win_regedit:
        path: "HKLM:\\Software\\Example"
    - name: modifying the registry adding name data and type
      win_regedit:
        path: "HKLM:\\Software\\Example"
        name: Ansible
        data: playbook
        type: Documents yml
